version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: jlpt-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongP@ssw0rd!123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"StrongP@ssw0rd!123\" -C -Q \"IF NOT EXISTS(SELECT * FROM sys.databases WHERE name='JLPT_LearningDB') CREATE DATABASE JLPT_LearningDB\" && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"StrongP@ssw0rd!123\" -C -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: jlpt-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: jlpt-backend
    env_file:
      - path: ./apps/backend/.env
        required: false
    environment:
      - UPLOAD_DIR=/app/uploads
      - DATABASE_URL=jdbc:sqlserver://db:1433;databaseName=JLPT_LearningDB;encrypt=true;trustServerCertificate=true
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=StrongP@ssw0rd!123
    volumes:
      - jlpt-uploads:/app/uploads
    restart: unless-stopped
    ports:
      - "8080:8080" # Cho phép truy cập backend trực tiếp nếu cần thiết trong lúc dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: jlpt-frontend
    ports:
      - "80:80" # Expose frontend ra cổng 80 (HTTP mặc định)
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  jlpt-uploads:
    name: jlpt-uploads
  sqlserver_data:
    name: sqlserver_data
