# -*- coding: utf-8 -*-
import sys, copy
sys.path.insert(0, r".skill/docx-report/scripts")
from docx_tools import *
from docx.oxml.ns import qn

doc = Document("docs/07-Release-Documents/RDS_Document.docx")

# ---- 0. Xoa cac doan huong dan (instructional text) khong can trong output ----
def del_by_text(doc, substr, occurrence=0):
    children = list(doc.element.body.iterchildren())
    i = find_paragraph_index(doc, substr, occurrence)
    children[i].getparent().remove(children[i])

def del_range_before(doc, start_substr, end_substr):
    """Xoa moi phan tu tu start_substr (inclusive) den truoc end_substr (exclusive)."""
    children = list(doc.element.body.iterchildren())
    i1 = find_paragraph_index(doc, start_substr)
    i2 = find_paragraph_index(doc, end_substr)
    for c in children[i1:i2]:
        c.getparent().remove(c)

# xoa khoi "Functional Description Contents" (huong dan dai)
del_range_before(doc, "Functional Description Contents", "b. Business Rules")
# xoa cau huong dan truoc bang Functional Description
del_by_text(doc, "Provide the functional description for the use cases")
# xoa cau huong dan truoc bang Business Rules
del_by_text(doc, "Provide the business rules those are applied only to the use case")

# ---- 1. repeat_block cho 26 UC ----
N = 26
ranges = repeat_block(doc, "1.1 <<UseCaseCode_UC Name>>", "Password Encoding", N)

UCS = [
dict(code="UC-01", name="User Login (Đăng nhập)", created_by="Minh Pham (suy từ git log)", date="2026-05-28",
     actor="Student (Khách)", sec_actor="Google OAuth Provider",
     trigger="User bấm 'Đăng nhập' từ header, hoặc truy cập route yêu cầu đăng nhập",
     desc="Student đăng nhập bằng Email/Mật khẩu hoặc Google OAuth để truy cập tính năng học tập cá nhân hoá.",
     pre="PRE-1: Tài khoản tồn tại & status=active. PRE-2: Hệ thống không ở chế độ bảo trì.",
     post="POST-1: Nhận accessToken+refreshToken (JWT), điều hướng /dashboard. POST-2: refreshToken lưu auth_tokens, hết hạn sau 7 ngày. POST-3: login_attempts reset về 0.",
     normal="1.0 Login: 1) Truy cập /login 2) Nhập Email+Mật khẩu 3) Bấm Đăng nhập 4) AuthenticationManager xác thực (xem Exceptions) 5) Sinh access+refresh token, lưu auth_tokens 6) Điều hướng /dashboard",
     alt="1.1 Google Login: bấm nút Google, GoogleLogin component trả credential (ID token) qua @react-oauth/google (client-side, KHÔNG dùng redirect/callback server-side) -> loginWithGoogle() verify qua GoogleIdTokenVerifier, tìm/tạo student_users theo oauth_provider_id -> tiếp bước 5 luồng chính.",
     exc="1.0.E1 Sai mật khẩu -> tăng login_attempts, >=5 lần liên tiếp khoá 15 phút -> 401 INVALID_CREDENTIALS. 1.0.E2 Đang bị khoá -> 429 TOO_MANY_REQUESTS. 1.0.E3 SUSPENDED -> 403 ACCOUNT_SUSPENDED. 1.0.E4 PENDING (chưa xác minh email) -> 403 EMAIL_NOT_VERIFIED. 1.0.E5 Bảo trì -> 503 MAINTENANCE_MODE.",
     priority="Must Have", freq="Cao nhất hệ thống — mọi Student đăng nhập >=1 lần/phiên",
     other="Refresh token hết hạn sau 7 ngày (hard-code trong AuthenticationService).",
     assumptions="Chưa có MFA cho Student (khác Admin).",
     biz=[("BIZ-AUTH-01","JWT bắt buộc","Mọi API trừ /api/auth/* phải qua JWT filter"),
          ("BIZ-AUTH-02","Mã hoá mật khẩu","bcrypt cost >= 10 (chuẩn dự án: 12)"),
          ("—","Khoá tài khoản 5 lần/15 phút","Có trong code (AuthenticationService), CHƯA có ID chính thức trong constraints/business.md — cần bổ sung")]),
dict(code="UC-02", name="User Register (Đăng ký tài khoản)", created_by="Không nêu", date="Cập nhật 2026-07-12",
     actor="Khách (Guest)", sec_actor="Hệ thống Email",
     trigger="Khách điền và gửi form đăng ký",
     desc="Khách tạo tài khoản mới bằng Email/Mật khẩu, xác minh bằng mã OTP 6 số qua email trước khi đăng nhập được.",
     pre="Email chưa tồn tại trong student_users; hệ thống gửi email hoạt động bình thường.",
     post="Thành công đăng ký: student_users mới status=pending, gửi OTP. Thành công xác minh: status=active, xoá OTP.",
     normal="1) Điền họ tên/email/mật khẩu/xác nhận 2) POST /api/auth/register 3) Validate 4) Kiểm tra email chưa tồn tại 5) Hash bcrypt (cost>=10) 6) Tạo student_users status=pending 7) Sinh OTP 6 số hết hạn 10 phút, lưu auth_tokens 8) Gửi email OTP 9) Trả 201 10) Điều hướng /verify-email",
     alt="A) Xác minh OTP: nhập mã, khớp/còn hạn -> active hoá, xoá token, 200. B) Gửi lại OTP: rate limit >=60s, xoá token cũ, sinh OTP mới, luôn trả 200.",
     exc="Email đã tồn tại -> 409 EMAIL_EXISTS. Mật khẩu yếu -> 422 WEAK_PASSWORD. OTP hết hạn -> 400 OTP_EXPIRED. Sai OTP >5 lần -> 429 TOO_MANY_ATTEMPTS.",
     priority="Must Have (P0)", freq="Không nêu",
     other="POST /api/auth/register; /verify-email; /resend-verification",
     assumptions="Không nêu",
     biz=[("BR-02-01","Trạng thái pending mặc định","Tài khoản mới luôn status=pending, bắt buộc xác minh email trước khi đăng nhập"),
          ("BR-02-03","OTP 6 số","SecureRandom, hết hạn 10 phút (FR-AUTH-13)"),
          ("BR-02-06","Giới hạn nhập sai OTP","Tối đa 5 lần sai -> xoá token, bắt buộc gửi lại mã mới"),
          ("BR-02-08","Chống email enumeration","Gửi lại OTP luôn trả HTTP 200 dù tài khoản không tồn tại")]),
dict(code="UC-03", name="Reset Password (Khôi phục mật khẩu)", created_by="Không nêu", date="Cập nhật 2026-05-30",
     actor="Khách/Student (quên mật khẩu)", sec_actor="Hệ thống Email",
     trigger="Nhấn 'Quên mật khẩu?' trên trang đăng nhập",
     desc="Người dùng yêu cầu đặt lại mật khẩu qua email; hệ thống gửi liên kết bảo mật hạn 15 phút.",
     pre="Người dùng có quyền truy cập hộp thư email đã đăng ký.",
     post="Thành công: password_hash cập nhật bcrypt; toàn bộ token session/password_reset bị thu hồi.",
     normal="1) Nhấn Quên mật khẩu 2) Nhập email, POST /api/auth/forgot-password 3) Validate + rate limit (<=3/email/giờ) 4) Luôn trả 200 (chống enumeration) 5) Nếu tìm thấy: thu hồi token cũ, tạo token mới (>=32 bytes, hạn 15 phút), gửi email",
     alt="A) Đặt mật khẩu mới: mở liên kết, POST /api/auth/reset-password {token, newPassword}; validate token còn hạn/chưa dùng, hash mật khẩu mới, thu hồi mọi token session/password_reset, trả 200.",
     exc="Token hết hạn/đã dùng -> 400 INVALID_TOKEN. Vượt rate limit -> 429 TOO_MANY_REQUESTS.",
     priority="Should Have (P1)", freq="Không nêu",
     other="POST /api/auth/forgot-password; /reset-password",
     assumptions="Không nêu",
     biz=[("BR-03-01","Chống enumeration","Luôn trả HTTP 200 cho forgot-password"),
          ("BR-03-02","Token hết hạn 15 phút","Theo FR-AUTH-20"),
          ("BR-03-05","Thu hồi mọi session","Sau khi đặt lại thành công, buộc đăng nhập lại trên mọi thiết bị"),
          ("BR-03-06","Rate limit","Tối đa 3 yêu cầu/email/giờ")]),
dict(code="UC-04", name="User Profile (Hồ sơ cá nhân)", created_by="Không nêu", date="Cập nhật 2026-05-30",
     actor="Student đã đăng nhập", sec_actor="Dịch vụ Lưu trữ File (S3/uploads)",
     trigger="Truy cập trang hồ sơ / chỉnh sửa & lưu / chọn ảnh đại diện mới",
     desc="Học viên xem/cập nhật hồ sơ (họ tên, avatar, SĐT, sinh nhật, tiểu sử, target JLPT level) và tải ảnh đại diện.",
     pre="JWT hợp lệ chứa student_id.",
     post="Xem: không đổi dữ liệu. Cập nhật: student_users cập nhật trường cho phép. Upload avatar: file lưu storage, avatar_url cập nhật.",
     normal="A-Xem: GET /api/students/me -> xác thực JWT -> map StudentProfileResponse -> 200. B-Cập nhật: PUT /api/students/me -> validate -> bỏ qua trường bất biến -> cập nhật partial -> 200.",
     alt="Upload avatar: POST /api/students/me/avatar (multipart) -> validate định dạng/kích thước/magic bytes -> lưu /uploads hoặc S3 -> cập nhật avatar_url -> 200.",
     exc="JWT hết hạn/thiếu -> 401 UNAUTHORIZED. Validation lỗi -> 400 VALIDATION_FAILED. File ảnh không hợp lệ -> 400 VALIDATION_FAILED.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET/PUT /api/students/me; POST /api/students/me/avatar",
     assumptions="Không nêu",
     biz=[("BR-04-01","Chỉ sửa hồ sơ chính mình","student_id lấy từ JWT, không nhận từ client"),
          ("BR-04-02","Trường bất biến","email, role, student_id, status, current_jlpt_level không đổi qua endpoint này"),
          ("BR-04-04","Không BLOB avatar","Chỉ lưu URL, không lưu BLOB trong DB")]),
dict(code="UC-05", name="Change Password (Đổi mật khẩu)", created_by="Không nêu", date="Cập nhật 2026-05-30",
     actor="Student đã đăng nhập", sec_actor="Không nêu",
     trigger="Truy cập 'Đổi mật khẩu' trong cài đặt tài khoản",
     desc="Học viên đang đăng nhập chủ động đổi mật khẩu bằng cách xác minh mật khẩu hiện tại (khác UC-03 dùng khi quên mật khẩu).",
     pre="JWT hợp lệ; tài khoản có password_hash (không áp dụng OAuth thuần).",
     post="Thành công: password_hash cập nhật, password_changed_at=NOW(), thu hồi các session khác (giữ session hiện tại).",
     normal="1) Vào mục Đổi mật khẩu 2) Điền 3 trường, PUT /api/students/me/password 3) Xác thực JWT 4) Validate mật khẩu mới 5) Xác minh mật khẩu hiện tại (bcrypt.compare) 6) Kiểm tra khác mật khẩu cũ 7) Hash & cập nhật 8) Thu hồi session khác 9) Trả 200",
     alt="Không có luồng phụ riêng.",
     exc="Mật khẩu hiện tại sai -> 400 WRONG_PASSWORD. Mật khẩu mới giống cũ -> 422 SAME_PASSWORD. Tài khoản OAuth -> 422 BUSINESS_RULE_VIOLATION. Mật khẩu yếu -> 422 WEAK_PASSWORD.",
     priority="Could Have (P2)", freq="Không nêu",
     other="PUT /api/students/me/password",
     assumptions="Không nêu",
     biz=[("BR-05-01","Xác minh mật khẩu hiện tại","Bắt buộc trước khi cho đổi"),
          ("BR-05-02","Không trùng mật khẩu cũ","Theo FR-AUTH-43"),
          ("BR-05-03","Giữ session hiện tại","Thu hồi các session khác, không đăng xuất thiết bị đang dùng")]),
dict(code="UC-06", name="Learn Grammar (Học ngữ pháp)", created_by="Không nêu", date="Cập nhật 2026-06-16",
     actor="Student đã đăng nhập", sec_actor="Staff (tạo/duyệt nội dung — ngoài phạm vi)",
     trigger="Student chọn cấp độ JLPT tại trang Ngữ pháp",
     desc="Học viên chọn cấp độ, xem danh sách/chi tiết ngữ pháp (cấu trúc, nghĩa, ví dụ song ngữ) và đánh dấu đã học.",
     pre="Tồn tại grammar_points published/is_deleted=0 ở cấp độ chọn.",
     post="Đánh dấu hoàn thành -> upsert student_content_progress(content_type=grammar); cập nhật last_activity_date.",
     normal="1) Chọn level 2) GET /api/grammar-points?level= 3) Query published 4) LEFT JOIN progress gắn isCompleted 5) Trả 200 6-10) Xem chi tiết GET .../{id}, đánh dấu học POST /api/learning-progress -> upsert progress",
     alt="Lọc theo level khác/phân trang -> lặp lại query danh sách.",
     exc="Level không hợp lệ -> 422 LEVEL_MISMATCH. Nội dung không tồn tại/chưa duyệt -> 404 CONTENT_NOT_FOUND. Input sai -> 400 VALIDATION_FAILED. Hạ tiến độ thủ công -> 422 PROGRESS_REGRESSION. VIP required -> 403 VIP_REQUIRED.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET /api/grammar-points; GET /api/grammar-points/{id}; POST /api/learning-progress",
     assumptions="Không nêu",
     biz=[("BR-06-01","Chỉ nội dung published","status=published và is_deleted=0"),
          ("BR-06-03","Tiến độ chỉ tăng","progress_percent/status không giảm thủ công"),
          ("BR-06-05","Kiểm soát VIP","is_vip_only=1 chỉ hiển thị khi Student có VIP hiệu lực")]),
dict(code="UC-07", name="Learn Kanji (Học chữ Hán)", created_by="Không nêu", date="Cập nhật 2026-06-16",
     actor="Student đã đăng nhập", sec_actor="Staff; CDN/Storage (stroke_order_url ảnh tĩnh)",
     trigger="Student chọn cấp độ JLPT tại trang Kanji",
     desc="Học viên xem danh sách/chi tiết Kanji (ký tự, số nét, ảnh thứ tự nét tĩnh, âm đọc, nghĩa, ví dụ), đánh dấu đã học, thêm Flashcard.",
     pre="Tồn tại kanji published ở cấp độ chọn.",
     post="Đánh dấu học -> upsert progress(content_type=kanji). Add to Flashcard -> tạo bản ghi flashcards.",
     normal="1) Chọn level 2) GET /api/kanji?level= 3) Trả danh sách+isCompleted 4-7) Chi tiết GET /api/kanji/{id} 8-10) Đánh dấu học POST /api/learning-progress 11-14) Add Flashcard POST /api/flashcards -> 201",
     alt="Không nêu chi tiết (lọc bộ thủ/tìm kiếm, tham chiếu SPEC riêng).",
     exc="Level sai -> 422 LEVEL_MISMATCH. Không tồn tại -> 404 CONTENT_NOT_FOUND. VIP required -> 403. Flashcard trùng -> 409 FLASHCARD_EXISTS. Hạ tiến độ -> 422 PROGRESS_REGRESSION.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET /api/kanji, /api/kanji/{id}; POST /api/learning-progress, /api/flashcards",
     assumptions="Không nêu",
     biz=[("BR-07-01","Chỉ published","status=published, is_deleted=0"),
          ("BR-07-02","Stroke order chỉ ảnh tĩnh","Không animation, không đánh giá thứ tự nét"),
          ("BR-07-05","Add to Flashcard","content_type=kanji, trùng -> 409")]),
dict(code="UC-08", name="Learn Kana (Học bảng chữ cái Kana)", created_by="Không nêu", date="Cập nhật 2026-06-16",
     actor="Student đã đăng nhập", sec_actor="CDN/Storage (audio_url, stroke_order_url)",
     trigger="Student chọn Hiragana/Katakana tại trang Kana",
     desc="Học viên xem bảng Hiragana/Katakana đầy đủ, chi tiết ký tự (romaji, audio, ảnh nét tĩnh), đánh dấu đã học.",
     pre="Bảng kana_characters có dữ liệu cho kana_type tương ứng.",
     post="Đánh dấu học -> upsert progress(content_type=kana).",
     normal="1) Chọn Hiragana/Katakana 2) GET /api/kana?type= 3) Trả toàn bộ bảng (>=46 ký tự)+isCompleted 4-7) Xem chi tiết/nghe audio (client-side, không gọi API riêng) 8-11) Đánh dấu học POST /api/learning-progress",
     alt="Chuyển tab Hiragana/Katakana -> GET lại theo type mới.",
     exc="type không hợp lệ -> 400 VALIDATION_FAILED. contentId không tồn tại -> 404 CONTENT_NOT_FOUND.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET /api/kana?type=; POST /api/learning-progress",
     assumptions="Không nêu",
     biz=[("BR-08-01","Trả toàn bộ bảng, không phân trang","Bảng cố định <=~50 ký tự"),
          ("BR-08-02","Audio phát trực tiếp","Browser phát từ audio_url, không qua backend"),
          ("BR-08-07","Không VIP/published cho Kana","Toàn bộ bảng luôn công khai cho Student đã đăng nhập")]),
dict(code="UC-09", name="Vocabulary (Học từ vựng)", created_by="Không nêu", date="Cập nhật 2026-06-16",
     actor="Student đã đăng nhập", sec_actor="Staff; CDN/Storage (audio_url)",
     trigger="Student chọn cấp độ/chủ đề tại trang Từ vựng",
     desc="Học viên xem từ vựng theo cấp độ/chủ đề (word, furigana, nghĩa, audio, ví dụ song ngữ), đánh dấu đã học, thêm Flashcard.",
     pre="Tồn tại vocabulary published khớp filter.",
     post="Đánh dấu học -> upsert progress(content_type=vocabulary). Add Flashcard -> tạo bản ghi flashcards.",
     normal="1) Chọn level/topic 2) GET /api/vocabulary?level=&topic= 3) Trả danh sách+isCompleted 4-7) Chi tiết GET .../{id} 8-10) Đánh dấu học 11-14) Add Flashcard -> 201",
     alt="Không nêu chi tiết (tìm kiếm từ khoá, danh sách topic).",
     exc="Level sai -> 422 LEVEL_MISMATCH. Không tồn tại -> 404. VIP required -> 403. Flashcard trùng -> 409. Hạ tiến độ -> 422.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET /api/vocabulary, /{id}; POST /api/learning-progress, /api/flashcards",
     assumptions="Không nêu",
     biz=[("BR-09-01","Chỉ published","status=published, is_deleted=0"),
          ("BR-09-02","Lọc đồng thời topic+level","Hỗ trợ đồng thời 2 filter"),
          ("BR-09-08","Ví dụ song ngữ","example_sentence_jp + vi luôn trả cùng nhau")]),
dict(code="UC-10", name="Take JLPT Mock Test (Làm bài thi thử JLPT)", created_by="Không nêu", date="Cập nhật 2026-06-10",
     actor="Student đã đăng nhập", sec_actor="System (Auto-submit), AuditLogService",
     trigger="Nhấn 'Bắt đầu thi thử' sau khi chọn đề",
     desc="Học viên làm đề thi thử JLPT đủ 3 phần với timer đếm ngược; kết quả trả điểm từng phần, tổng điểm, đạt/không đạt.",
     pre="Đề tồn tại, assessment_type=exam, status=published; nếu is_vip_only cần subscription VIP.",
     post="Thành công: test_attempts mới (submitted/auto_submitted) + attempt_answers. Quá giờ (manual): 400, không tạo bản ghi.",
     normal="1) Lọc đề theo level 2) Chọn đề, Bắt đầu 3) Validate, tạo TestAttempt in_progress, started_at server-side, tính expiresAt, ẩn correctOption 4) Làm bài, Nộp bài 5) Validate attempt thuộc student & in_progress & còn giờ; tính điểm server-side; persist trong 1 transaction; audit log EXAM_SUBMITTED",
     alt="A) Auto-Submit hết giờ: isAutoSubmit=true, bỏ qua time validation, status=auto_submitted. B) Polling remainingSeconds khi reload.",
     exc="Nộp sau khi hết giờ (manual) -> 400 TIME_EXCEEDED. Không VIP -> 403 VIP_REQUIRED. Nộp lại đã submitted -> 422 ATTEMPT_ALREADY_SUBMITTED. Không phải attempt của mình -> 403 FORBIDDEN.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET /api/assessments?type=exam; POST /{id}/start; GET /api/test-attempts/{id}/status; POST /{id}/submit",
     assumptions="Không nêu",
     biz=[("BR-10-01","started_at server-side","Client không gửi timestamp"),
          ("BR-10-05","Score tính 100% server-side","Client không gửi score"),
          ("BR-10-07","Mỗi lần nộp = attempt mới","Không UPDATE bản ghi cũ"),
          ("BR-10-10","Chỉ nộp attempt của mình","attempt.student_id phải khớp JWT.studentId")]),
dict(code="UC-11", name="Quiz & Luyện Tập (Quiz & Practice)", created_by="Không nêu", date="Cập nhật 2026-06-10",
     actor="Student đã đăng nhập", sec_actor="AssessmentService, AuditLogService",
     trigger="Chọn 1 quiz, nhấn Bắt đầu",
     desc="Học viên chọn quiz/phiên luyện tập ngắn (10-20 câu), làm bài, nhận kết quả tức thì kèm giải thích từng câu.",
     pre="Quiz tồn tại, published; VIP nếu is_vip_only.",
     post="Thành công: test_attempts submitted + attempt_answers. Nộp lại -> 422, bản ghi cũ không đổi.",
     normal="1) Chọn level/kỹ năng, xem danh sách 2) Chọn quiz, Bắt đầu 3) Tạo TestAttempt in_progress, ẩn correctOption 4) Làm bài, Nộp bài 5) Validate + tính điểm server-side + batch insert attempt_answers + audit log QUIZ_SUBMITTED 6) Hiển thị kết quả",
     alt="Luyện tập ngẫu nhiên (practice type): assessment_type=practice, có thể không giới hạn thời gian.",
     exc="Nộp lại attempt đã submitted -> 422 ATTEMPT_ALREADY_SUBMITTED. Quiz không tồn tại -> 404. Score invariant vi phạm -> 422 SCORE_INVARIANT_VIOLATION.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET /api/assessments; POST /{id}/start, /{id}/submit; GET /api/test-attempts",
     assumptions="Không nêu",
     biz=[("BR-11-01","Không lộ đáp án đúng","QuestionResponse DTO không chứa correct_option trước khi nộp"),
          ("BR-11-03","Mỗi lần nộp = attempt mới","Bất biến hoàn toàn"),
          ("BR-11-07","So sánh fill_blank","Case-insensitive, trim")]),
dict(code="UC-13", name="Speaking Practice & AI Grading (Luyện nói & AI chấm điểm)", created_by="Không nêu", date="Cập nhật 2026-06-17",
     actor="Student (có microphone)", sec_actor="AI Engine (Speech Recognition, abstract qua interface); Staff (override điểm, ngoài phạm vi)",
     trigger="Nhấn 'Nộp bài' với file audio đã ghi âm",
     desc="Học viên nghe mẫu, ghi âm, nộp lên hệ thống; xử lý bất đồng bộ qua AI, trả điểm phát âm/lưu loát/lỗi/gợi ý.",
     pre="Bài học lesson_type=speaking, published; Student có microphone.",
     post="Nộp: student_submissions (speaking, pending) tạo mới, job AI enqueue, trả 202. Kết quả: cập nhật điểm AI, status=ai_graded.",
     normal="1) Xem prompt+audio mẫu 2) Ghi âm, Nộp bài 3) Validate file (mp3/wav/webm <=10MB), lưu URL 4) Tạo submission pending, enqueue AI job, trả 202 ngay (không chờ AI) 5) AI Engine (background) phân tích, tính điểm 6) Cập nhật status=ai_graded 7) Student poll kết quả",
     alt="AI Fail & Fallback: retry 1s/2s/4s (tối đa 3 lần); fail hết -> status=ai_graded, ai_suggestions='Không thể xử lý...', log đầy đủ.",
     exc="File sai định dạng -> 400 INVALID_FILE_TYPE. >10MB -> 400 FILE_TOO_LARGE. lessonId không tồn tại/không phải speaking -> 404 LESSON_NOT_FOUND. AI fail 3 lần -> fallback nội bộ.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET /api/lessons/{id}/speaking; POST /api/submissions/speaking; GET /api/submissions/{id}/result",
     assumptions="Không nêu",
     biz=[("BR-13-01","Không BLOB file audio","Chỉ lưu URL/path"),
          ("BR-13-02","Trả 202 ngay","Không chờ AI xử lý"),
          ("BR-13-03","Timeout+retry","30s/lần, tối đa 3 lần, backoff 1s/2s/4s"),
          ("BR-13-06","Staff override","final_score = manual_score ?? ai_overall_score")],
     note="LƯU Ý TRIỂN KHAI THỰC TẾ (nguyên văn tài liệu nguồn): \"AI Engine — abstract qua interface — engine cụ thể chưa chốt\"; Out of Scope ghi rõ chưa chọn AI engine cụ thể."),
dict(code="UC-14", name="Reading Practice (Luyện đọc hiểu)", created_by="Không nêu", date="Cập nhật 2026-06-19",
     actor="Student đã đăng nhập", sec_actor="Staff (tạo/duyệt nội dung, ngoài phạm vi)",
     trigger="Nhấn 'Nộp bài' sau khi trả lời câu hỏi bài đọc",
     desc="Học viên chọn bài đọc theo cấp độ, đọc đoạn văn tiếng Nhật, trả lời trắc nghiệm, nhận kết quả ngay.",
     pre="Tồn tại lessons lesson_type=reading, published, có >=1 câu hỏi qua question_assignments.",
     post="Nộp bài: test_attempts mới (attempt_type=reading) + attempt_answers; điểm tính server-side.",
     normal="1) Chọn level, tab Reading 2) Query lessons published, đếm questionCount, hasAttempted 3) Chọn bài đọc 4) Lấy câu hỏi (ẩn đáp án đúng) + passageText 5) Trả lời, Nộp bài 6) Validate, lấy correct_option từ DB, tính điểm server-side, tạo test_attempts+attempt_answers 7) Trả điểm+kết quả từng câu",
     alt="A) Lọc theo level/phân trang. B) Làm lại: tạo attempt MỚI, không update cũ, hasAttempted=true.",
     exc="Bài đọc không tồn tại/chưa duyệt -> 404 LESSON_NOT_FOUND. Request nộp bài sai -> 400 VALIDATION_FAILED. Score invariant vi phạm -> 422 SCORE_INVARIANT. VIP required -> 403 VIP_REQUIRED.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET /api/lessons?type=reading; GET /{id}/reading; POST /{id}/submit",
     assumptions="Không nêu",
     biz=[("BR-14-01","Chỉ published","lesson_type=reading, status=published"),
          ("BR-14-03","Điểm tính server-side","Client không gửi score"),
          ("BR-14-04","Mỗi lần nộp = attempt mới","Không UPDATE bản ghi cũ")]),
dict(code="UC-15", name="Listening Practice (Luyện nghe hiểu)", created_by="Không nêu", date="Cập nhật 2026-06-19",
     actor="Student đã đăng nhập", sec_actor="Staff; CDN/File Storage (audio_url)",
     trigger="Chọn cấp độ, tab Listening",
     desc="Học viên chọn bài nghe theo cấp độ, phát audio, trả lời trắc nghiệm, nhận kết quả kèm transcript.",
     pre="Tồn tại lessons lesson_type=listening published với audio_url hợp lệ và >=1 câu hỏi.",
     post="Nộp bài: test_attempts (attempt_type=listening) + attempt_answers; trả transcriptText nếu có.",
     normal="1) Chọn level, tab Listening 2) Query lessons published 3) Chọn bài nghe 4) Lấy audio_url + câu hỏi (ẩn đáp án) 5) Nghe (client-side play/pause/replay), Nộp bài 6) Validate, tính điểm server-side, lấy transcriptText từ content_text 7) Trả điểm+transcript+kết quả",
     alt="A) Lọc/phân trang. B) Replay audio (client-side, không gọi API). C) Làm bài lần 2: tạo attempt MỚI.",
     exc="Lesson không tồn tại/chưa duyệt -> 404 LESSON_NOT_FOUND. Request sai -> 400 VALIDATION_FAILED. Score invariant -> 422 SCORE_INVARIANT. VIP required -> 403 VIP_REQUIRED.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET /api/lessons?type=listening; GET /{id}/listening; POST /{id}/submit",
     assumptions="Không nêu",
     biz=[("BR-15-03","audio_url là URL, không phải binary","Hosted /uploads hoặc S3, không stream trực tiếp từ Spring Boot"),
          ("BR-15-06","Mỗi lần nộp = attempt mới","Không UPDATE bản ghi cũ"),
          ("BR-15-10","Transcript thủ công","Staff tạo thủ công, không AI-generated")]),
dict(code="UC-18", name="Logout (Đăng xuất)", created_by="Không nêu", date="Cập nhật 2026-05-30",
     actor="Student đã đăng nhập", sec_actor="Không nêu",
     trigger="Nhấn 'Đăng xuất' (Header hoặc trang Cá nhân)",
     desc="Học viên chủ động đăng xuất để vô hiệu hoá token hiện tại của thiết bị đó.",
     pre="Đang ở trạng thái đã đăng nhập (sở hữu JWT/Refresh Token hợp lệ).",
     post="Thành công: token session hiện tại bị thu hồi (revoked_at=NOW()); client xoá token; điều hướng /login.",
     normal="1) Nhấn Đăng xuất 2) POST /api/auth/logout kèm JWT+refresh cookie 3) Xác thực JWT 4-5) Tìm bản ghi auth_tokens 6) Cập nhật revoked_at=NOW() 7) Xoá cookie refresh 8) Audit log LOGOUT_SUCCESS 9) Trả 200 10) Client xoá token, điều hướng /login",
     alt="Đăng xuất khi JWT đã hết hạn trên server: BE trả 401, FE fallback tự xoá token + điều hướng /login.",
     exc="Header Authorization thiếu/sai -> 401, client tự xoá session cục bộ. JWT hết hạn -> 401 UNAUTHORIZED.",
     priority="Should Have (P1)", freq="Không nêu",
     other="POST /api/auth/logout",
     assumptions="Không nêu",
     biz=[("BR-18-01","Thu hồi chính xác session","Chỉ vô hiệu hoá token hiện tại, không ảnh hưởng thiết bị khác"),
          ("BR-18-02","Làm sạch dữ liệu Client","Client luôn xoá token dù API trả 200 hay lỗi"),
          ("BR-18-04","Audit Log đầy đủ","Ghi IP, thời gian, User ID")]),
dict(code="UC-20", name="AI Handwriting Practice (Luyện viết chữ bằng AI — OCR)", created_by="Không nêu", date="Cập nhật 2026-06-17",
     actor="Student (có thiết bị cảm ứng/chuột)", sec_actor="AI Engine (OCR, abstract qua interface); Staff (override điểm, ngoài phạm vi)",
     trigger="Nhấn 'Nộp bài' sau khi vẽ ký tự trên Canvas",
     desc="Học viên chọn ký tự Kanji/Kana cần luyện, xem stroke order, vẽ lại trên Canvas, nộp PNG; hệ thống so sánh với ký tự chuẩn, trả similarity_percent.",
     pre="Ký tự mục tiêu tồn tại (kanji/kana_characters); Frontend render được Canvas và export PNG.",
     post="Nộp: student_submissions (handwriting, pending), job OCR enqueue, trả 202. Kết quả: recognized_character, similarity_percent, is_correct, status=ai_graded.",
     normal="1) Chọn ký tự, xem stroke_order_url 2) Vẽ, Nộp bài 3) Export Canvas->PNG kèm targetType/targetId/expectedCharacter 4) Validate file (png/jpg<=5MB), lưu URL 5) Tạo submission pending, enqueue OCR job, trả 202 ngay 6) OCR Engine (background) nhận diện, tính similarity_percent, is_correct=(similarity>=70) 7) Cập nhật status=ai_graded 8) Poll kết quả",
     alt="OCR Fail & Fallback: retry 1s/2s/4s (tối đa 3 lần); fail hết -> recognized_character=null, similarity_percent=0, is_correct=false, log đầy đủ.",
     exc="File sai định dạng -> 400 INVALID_FILE_TYPE. >5MB -> 400 FILE_TOO_LARGE. targetType sai -> 400 VALIDATION_FAILED. targetId không tồn tại -> 404.",
     priority="Should Have (P1)", freq="Không nêu",
     other="POST /api/submissions/handwriting; GET /api/submissions/{id}/result",
     assumptions="Không nêu",
     biz=[("BR-20-01","Không BLOB ảnh viết tay","Chỉ lưu URL/path (ADR-006)"),
          ("BR-20-03","OCR chỉ so sánh similarity %","Không phân tích stroke order/direction/thẩm mỹ (ADR-007)"),
          ("BR-20-04","Ngưỡng đúng/sai","is_correct=(similarity_percent>=70), có thể cấu hình")],
     note="LƯU Ý TRIỂN KHAI THỰC TẾ: file nguồn ghi \"AI Engine (OCR) — abstract qua interface — engine cụ thể chưa chốt\"; khớp với ADR-007 (BR-20-03)."),
dict(code="UC-24", name="Manage Question Bank (Quản lý ngân hàng câu hỏi)", created_by="Không nêu", date="Cập nhật 2026-06-12",
     actor="Staff", sec_actor="StaffManager (duyệt, ngoài phạm vi); Hệ thống",
     trigger="Staff cần tạo/xem/sửa/gửi duyệt câu hỏi",
     desc="Staff tạo, xem, sửa, tìm kiếm, lọc và gửi duyệt câu hỏi theo skill/jlpt_level; câu hỏi đã dùng trong attempt_answers bị khoá.",
     pre="Staff đã đăng nhập, role STAFF, status=active.",
     post="Thành công: bản ghi questions tạo/cập nhật/chuyển trạng thái, ghi log. Thất bại: rollback, không đổi dữ liệu.",
     normal="1) POST /api/staff/questions với question_text/type/skill/level 2) Validate theo question_type 3) Lưu status=draft, created_by 4) Xem danh sách (tìm kiếm+lọc) 5) Xem chi tiết kèm isLocked 6) Cập nhật (chỉ khi draft/rejected & chưa khoá) 7) Gửi duyệt POST /submit-review -> pending_review 8) Ghi log mọi hành động",
     alt="Không nêu luồng phụ riêng — file trình bày 4 nhóm chức năng (Tạo/Xem-Lọc/Cập nhật/Gửi duyệt).",
     exc="Thiếu trường bắt buộc -> 400 VALIDATION_FAILED. question_type/skill/jlpt_level sai -> 400. Không phải chủ sở hữu -> 403 FORBIDDEN. Câu hỏi đã trong attempt_answers, sửa trực tiếp -> 409 QUESTION_LOCKED. Sai trạng thái -> 409 INVALID_STATUS_TRANSITION.",
     priority="Không nêu", freq="Không nêu",
     other="POST/GET/PUT /api/staff/questions[/{id}]; POST /api/staff/contents/submit-review",
     assumptions="Không nêu",
     biz=[("—","Không có ID BR-xx-xx","File dùng mã FR-24-01..FR-24-25 thay Business Rules — không tự đặt ID mới")]),
dict(code="UC-25", name="Manage Grammar Content (Quản lý nội dung ngữ pháp)", created_by="Không nêu", date="Cập nhật 2026-06-12",
     actor="Staff (staff_role=staff)", sec_actor="Staff Manager (kế thừa quyền, duyệt thuộc UC khác); System",
     trigger="Staff cần tạo/xem/sửa/liên kết lesson/gửi duyệt 1 điểm ngữ pháp",
     desc="Staff tạo, xem, sửa, liên kết lesson và gửi duyệt các điểm ngữ pháp JLPT; nội dung mới luôn draft.",
     pre="Đã đăng nhập, JWT hợp lệ, staff_users.status=active.",
     post="Nội dung mới luôn draft; toàn vẹn jlpt_level; chỉ StaffManager/Admin mới publish.",
     normal="1) POST /api/staff/grammar (structure, meaning, usageExplanation, ví dụ, jlptLevel) 2) Validate + jlptLevel hợp lệ 3) Nếu có lessonId, xác minh cùng jlpt_level 4) Lưu status=draft 5) Xem danh sách/chi tiết 6) Cập nhật (chỉ draft/rejected) 7) Gửi duyệt -> pending_review 8) Log GRAMMAR_CREATED/UPDATED/SUBMITTED",
     alt="Không nêu luồng phụ riêng.",
     exc="JWT thiếu/hết hạn -> 401. Sai role/không sở hữu -> 403. Thiếu trường -> 400. lesson.jlpt_level khác grammar.jlpt_level -> 422. Sửa khi published -> 422 ERR-STATE-EDIT.",
     priority="Không nêu", freq="Không nêu",
     other="POST/GET/PUT /api/staff/grammar[/{id}]; POST /api/staff/contents/submit-review",
     assumptions="Backend Spring Boot 3.x, response chuẩn {status,message,data}, DTO Pattern bắt buộc, soft delete toàn hệ thống.",
     biz=[("—","Không có ID BR-xx-xx","File dùng mã FR-01..FR-22 và NFR-01..NFR-10 — không tự đặt ID mới")]),
dict(code="UC-26", name="Manage Quiz (Quản lý bài Quiz)", created_by="Không nêu", date="Cập nhật 2026-06-12",
     actor="Staff", sec_actor="StaffManager (duyệt, ngoài phạm vi); Hệ thống",
     trigger="Staff tạo khung quiz/gán câu hỏi/gửi duyệt",
     desc="Staff tạo quiz (assessment_type=quiz), gán câu hỏi kèm display_order/score, gửi duyệt; Σscore phải khớp total_score trước khi duyệt.",
     pre="Staff đã đăng nhập, role STAFF, status=active.",
     post="Thành công: assessments (quiz) + question_assignments tạo/cập nhật; log mọi thao tác.",
     normal="1) POST /api/staff/assessments (title, jlptLevel, duration, passScore, totalScore) 2) Validate range 3) Lưu draft 4) Xem/lọc danh sách 5) Xem chi tiết (assignedScoreSum, scoreMatched) 6) Cập nhật metadata (chỉ draft/rejected) 7) Gán câu hỏi POST /assign-questions (thay thế toàn bộ set) 8) Gửi duyệt -> kiểm tra Σscore=total_score, có >=1 câu -> pending_review",
     alt="Không nêu luồng phụ riêng.",
     exc="Thiếu trường/range sai -> 400 VALIDATION_FAILED. Gán trùng question_id -> 409 DUPLICATE_ASSIGNMENT. Sửa khi published -> 409 ASSESSMENT_PUBLISHED. Σscore != total_score khi duyệt -> 422 SCORE_MISMATCH. Quiz chưa có câu hỏi -> 422 EMPTY_QUIZ.",
     priority="Không nêu", freq="Không nêu",
     other="POST/GET/PUT /api/staff/assessments[/{id}]; POST /{id}/assign-questions; POST /api/staff/contents/submit-review",
     assumptions="Không nêu",
     biz=[("—","Không có ID BR-xx-xx","File dùng mã FR-26-01..FR-26-33, bất biến Σscore=total_score ở §5.3")]),
dict(code="UC-27", name="Manage Learning Content (Quản lý nội dung bài học)", created_by="Không nêu", date="Cập nhật 2026-06-12",
     actor="Staff", sec_actor="StaffManager (duyệt, ngoài phạm vi); Hệ thống",
     trigger="Staff tạo/cập nhật học liệu (lesson/vocabulary/kanji) rồi gửi duyệt",
     desc="Staff tạo và cập nhật 3 loại học liệu (lesson, vocabulary, kanji) ở trạng thái draft, media lưu dạng URL, gửi sang pending_review.",
     pre="Staff đã đăng nhập, role STAFF, status=active.",
     post="Thành công: lessons/vocabulary/kanji tạo/cập nhật/chuyển trạng thái; log created_by/updated_at.",
     normal="1) POST /api/staff/lessons (title, lessonType, jlptLevel, content) 2) POST /api/staff/vocabulary (word, meaning, furigana) 3) POST /api/staff/kanji (characterValue unique, meaning) 4) Cập nhật (chỉ draft/rejected & thuộc sở hữu) 5) Gửi duyệt -> pending_review 6) Log mọi hành động",
     alt="Không nêu luồng phụ riêng (4 nhóm chức năng: Lesson/Vocabulary/Kanji/Gửi duyệt).",
     exc="Thiếu trường -> 400 VALIDATION_FAILED. Lesson thiếu nội dung (listening thiếu audioUrl) -> 400 LESSON_CONTENT_REQUIRED. characterValue trùng -> 409 KANJI_DUPLICATE. Sai trạng thái -> 409 INVALID_STATUS_TRANSITION.",
     priority="Không nêu", freq="Không nêu",
     other="POST /api/staff/lessons; /vocabulary; /kanji; POST /api/staff/contents/submit-review",
     assumptions="Không nêu",
     biz=[("—","Không có ID BR-xx-xx","File dùng mã FR-27-01..FR-27-26 — không tự đặt ID mới")]),
dict(code="UC-28", name="Manage JLPT Mock Exams (Quản lý đề thi thử JLPT)", created_by="Không nêu", date="2026-06-12",
     actor="Staff", sec_actor="StaffManager (duyệt/publish, ngoài phạm vi); Hệ thống",
     trigger="Staff soạn/gửi 1 đề thi thử JLPT mới",
     desc="Staff tạo khung đề thi (assessment_type=exam) draft, chia section, gán câu hỏi, gửi duyệt pending_review. Staff không được tự publish.",
     pre="Staff đã đăng nhập, JWT hợp lệ, role STAFF, status=active.",
     post="Thành công: assessments (exam) tạo/cập nhật/chuyển trạng thái; question_assignments tạo/thay thế theo section.",
     normal="1) POST /assessments (title, jlptLevel, durationMin, passScore, totalScore) -> assessmentType=exam, status=draft 2) Xem danh sách/chi tiết theo section 3) Chia section+gán câu hỏi published cùng level (POST /assign-questions, replace semantics) 4) Cập nhật metadata (chỉ draft/rejected) 5) Gửi duyệt (kiểm tra Σscore=totalScore, >=1 câu) -> pending_review",
     alt="Xem/lọc theo jlptLevel/status; cập nhật chỉ hợp lệ khi draft/rejected; khoá thay đổi khi đã published.",
     exc="Thiếu trường/range sai -> 400 VALIDATION_FAILED. Cố đặt status=published -> 403 PUBLISH_NOT_ALLOWED. Gán trùng câu hỏi -> 409 DUPLICATE_ASSIGNMENT. Σscore không khớp -> 422 SCORE_MISMATCH. Đề chưa có câu hỏi khi gửi duyệt -> 422 EMPTY_EXAM.",
     priority="Không nêu", freq="Không nêu",
     other="POST/GET/PUT /api/staff/assessments[/{id}]; POST /{id}/assign-questions; POST /api/staff/contents/submit-review",
     assumptions="Không nêu",
     biz=[("—","Không có ID BR-xx-xx","File chỉ tham chiếu inline \"Rule 1\"-\"Rule 10\", không có bảng BR-28-xx")]),
dict(code="UC-33", name="Review Submitted Content (Duyệt nội dung Staff gửi)", created_by="Không nêu", date="2026-06-12",
     actor="StaffManager", sec_actor="Staff (người soạn/nhận feedback); Hệ thống",
     trigger="StaffManager mở Review Queue và Approve/Reject/Request Changes",
     desc="StaffManager xem hàng đợi và chi tiết nội dung pending_review, quyết định Approve/Reject/Request Changes; nguyên tắc bốn mắt (không tự duyệt nội dung mình tạo).",
     pre="Đã đăng nhập, role Staff với staff_role=staff_manager, status=active.",
     post="Approve: status=published, approved_by, published_at, audit log. Reject/Request Changes: status=rejected/draft, feedback lưu audit log.",
     normal="1) GET /api/manager/review-queue (phân trang, sort updated_at tăng dần) 2) Xem chi tiết GET /contents/{id} 3) POST /reviews Approve -> published 4) hoặc Reject (bắt buộc feedback) -> rejected 5) hoặc Request Changes POST /reviews/request-changes (bắt buộc feedback) -> draft/rejected theo targetStatus 6) Kiểm tra reviewer != người tạo (four-eyes) + status vẫn pending_review tại thời điểm commit, ghi audit log cùng transaction",
     alt="Approve: feedback không bắt buộc. Reject/Request Changes: feedback bắt buộc.",
     exc="Thiếu feedback khi Reject/Request Changes -> 400 FEEDBACK_REQUIRED. Không phải staff_manager -> 403 FORBIDDEN. Tự duyệt nội dung của chính mình -> 403 SELF_REVIEW_DENIED. Nội dung đã bị reviewer khác xử lý -> 409 CONCURRENT_REVIEW.",
     priority="Không nêu", freq="Không nêu",
     other="GET /api/manager/review-queue; GET /contents/{id}; POST /reviews; POST /reviews/request-changes",
     assumptions="Không nêu",
     biz=[("—","Không có ID BR-xx-xx","File chỉ tham chiếu inline \"Rule 1\"-\"Rule 10\", không có bảng BR-33-xx")]),
dict(code="UC-34", name="Manage Published Content Status (Quản lý trạng thái xuất bản)", created_by="Không nêu", date="2026-06-12",
     actor="StaffManager", sec_actor="Staff (nhận lại draft khi unpublish); Student (không thấy nội dung ẩn); Hệ thống",
     trigger="StaffManager chọn 1 nội dung published, thực hiện Unpublish/Archive/Delete/Restore",
     desc="StaffManager điều phối vòng đời sau xuất bản qua soft delete: Unpublish (về draft), Archive, Delete (xoá mềm), Restore (archived->published); chặn nếu đang bị tham chiếu.",
     pre="Đã đăng nhập, role Staff với staff_role=staff_manager, status=active.",
     post="Unpublish: status=draft. Archive: status=archived. Delete: status=deleted (không xoá vật lý). Restore: archived->published. Mọi thao tác ghi audit log.",
     normal="1) GET /published-contents (phân trang, published_at giảm dần) 2) Xem chi tiết kèm references (tài nguyên đang phụ thuộc) 3) PUT /contents/{id}/status (kèm reason bắt buộc) 4) Kiểm tra ràng buộc tham chiếu trong cùng transaction; nếu có tham chiếu chặn -> từ chối 5) Cập nhật status, ghi audit log, loại khỏi Student-facing ngay 6) Restore archived -> published qua POST /restore",
     alt="Restore bị chặn nếu nội dung đã deleted (trạng thái cuối) -> 409 RESTORE_NOT_ALLOWED. RESOURCE_IN_USE khi câu hỏi đang trong đề published.",
     exc="Thiếu/rỗng reason -> 400 REASON_REQUIRED. Không phải staff_manager -> 403 FORBIDDEN. Đang bị tham chiếu bởi tài nguyên active -> 409 RESOURCE_IN_USE. Restore nội dung deleted -> 409 RESTORE_NOT_ALLOWED.",
     priority="Không nêu", freq="Không nêu",
     other="GET /api/manager/published-contents; GET /contents/{id}; PUT /{id}/status; POST /{id}/restore",
     assumptions="Không nêu",
     biz=[("—","Không có ID BR-xx-xx","File chỉ tham chiếu inline \"Rule 1\"-\"Rule 9\", không có bảng BR-34-xx")]),
dict(code="UC-35", name="Login System (Đăng nhập Admin Panel)", created_by="Không nêu", date="2026-06-03",
     actor="Khách (đăng nhập với tài khoản Admin)", sec_actor="Hệ thống",
     trigger="Admin điền email/mật khẩu vào form đăng nhập chung, nhấn Đăng nhập",
     desc="Admin dùng chung màn hình đăng nhập với role khác (POST /api/auth/login). Backend tự phát hiện role theo email (admin_users -> staff_users -> student_users), cấp JWT claim role=ADMIN.",
     pre="Admin có tài khoản trong admin_users, status=active.",
     post="Thành công: auth_tokens (refresh, actor_type=admin) tạo mới; JWT access token (15 phút, role=ADMIN); điều hướng /admin.",
     normal="1) Điền email/mật khẩu, Đăng nhập 2) POST /api/auth/login 3) Validate 4) Tra cứu email: admin_users -> staff_users -> student_users, tìm thấy ở admin_users -> luồng Admin 5) Kiểm tra locked_until 6) Kiểm tra status=active 7) So sánh mật khẩu bcrypt (cost>=12) 8) login_attempts=0, cập nhật last_login_at 9) Tạo JWT (15 phút, role=ADMIN) 10) Tạo refresh token (7 ngày) 11) Trả 200 12) Điều hướng /admin",
     alt="Multi-Role Detection: AuthService.login() thử lần lượt admin -> staff -> student; không tìm thấy -> InvalidCredentialsException, thông báo không tiết lộ role.",
     exc="Field sai định dạng -> 400 VALIDATION_FAILED. Sai mật khẩu/email không tồn tại -> 401 INVALID_CREDENTIALS. status=suspended -> 403 ACCOUNT_SUSPENDED. login_attempts>=5 (khoá 15 phút) -> 429 TOO_MANY_REQUESTS.",
     priority="Must Have (P0)", freq="Không nêu",
     other="POST /api/auth/login (dùng chung UC-01/UC-35); POST /api/auth/refresh; POST /api/auth/logout (UC-18)",
     assumptions="Không nêu",
     biz=[("BR-35-02","JWT Admin claim role=ADMIN","Spring Security kiểm tra claim trên mọi endpoint /api/admin/**"),
          ("BR-35-03","bcrypt cost >=12","Cao hơn mức tối thiểu 10 cho Student/Staff"),
          ("BR-35-06","Rate limit 5 req/phút/IP","Nghiêm ngặt hơn Student (10 req/phút)")]),
dict(code="UC-37", name="User Management (Quản lý người dùng)", created_by="Không nêu", date="2026-05-30",
     actor="Admin đã đăng nhập", sec_actor="Hệ thống Email (SMTP)",
     trigger="Admin chọn loại người dùng và thực hiện thao tác quản trị",
     desc="Admin quản lý toàn bộ tài khoản (Student/Staff/Admin): xem, tạo Staff mới, sửa, đình chỉ/kích hoạt, đặt lại mật khẩu qua email, xoá mềm, chuyển vai trò Staff.",
     pre="Admin đã đăng nhập, JWT role=ADMIN, status=active.",
     post="Thành công: dữ liệu cập nhật trong DB; mọi thao tác ghi admin_audit_logs.",
     normal="UC-37-01 GET /api/admin/users?type= (lọc/tìm/phân trang). UC-37-02 GET chi tiết. UC-37-03 POST /api/admin/staff tạo Staff (status=pending, gửi email mời). UC-37-04 PUT sửa (không tự sửa mình, không đổi email/role). UC-37-05 POST /suspend (reason bắt buộc, revoke session). UC-37-06 POST /activate. UC-37-07 POST /reset-password (qua email, không đặt trực tiếp). UC-37-08 DELETE xoá mềm. UC-37-09 PUT /staff/{id}/role đổi staff_role.",
     alt="Mỗi thao tác 37-01..09 là luồng độc lập; 2 sequence diagram minh hoạ: Đình chỉ tài khoản, Tạo Staff mới.",
     exc="Trường sai định dạng -> 400 VALIDATION_FAILED. Admin thao tác lên chính mình -> 403 SELF_MODIFICATION_FORBIDDEN. userId không tồn tại -> 404 USER_NOT_FOUND. Email trùng khi tạo Staff -> 409 EMAIL_EXISTS. Xoá Admin đang hoạt động -> 422 CANNOT_DELETE_ACTIVE_ADMIN.",
     priority="Should Have (P1)", freq="Không nêu",
     other="GET/PUT/DELETE /api/admin/users[/{type}/{id}]; POST /api/admin/staff; /suspend; /activate; /reset-password; PUT /api/admin/staff/{id}/role",
     assumptions="Không nêu",
     biz=[("BR-37-01","Không tự thao tác lên chính mình","Ngăn lock-out"),
          ("BR-37-02","Không đổi email qua API này","Cần quy trình xác minh riêng"),
          ("BR-37-05","Reset mật khẩu qua email","Không đặt trực tiếp — người dùng tự kiểm soát"),
          ("BR-37-09","Không trả password_hash/2FA secret","Trong bất kỳ response nào")]),
dict(code="UC-AUTH-06", name="Đặt Lại Mật Khẩu Staff (Admin-Mediated Reset) — cục bộ feat-auth, KHÔNG có trong danh mục UC-01→40 hợp nhất",
     created_by="Không nêu", date="2026-05-30",
     actor="Staff (yêu cầu) + Admin (phê duyệt & cấp mật khẩu tạm)", sec_actor="Email Service (SMTP)",
     trigger="Staff nhấn 'Quên mật khẩu?' trên trang đăng nhập chung",
     desc="Staff gửi yêu cầu reset; Admin nhận thông báo, sinh mật khẩu tạm gửi qua email; Staff đăng nhập bằng mật khẩu tạm rồi bắt buộc đổi mật khẩu mới. Khác UC-03: admin-mediated, không có magic link.",
     pre="Staff có staff_users status=active; Admin đã đăng nhập; SMTP hoạt động.",
     post="Thành công: staff_users.password_hash cập nhật, must_change_password=0, request status=completed. Thất bại/bỏ dở: mật khẩu tạm hiệu lực tới khi Admin thu hồi hoặc hết hạn 24h.",
     normal="1) Staff mở trang đăng nhập, Quên mật khẩu 2) POST /api/auth/check-account-type xác định accountType 3) FE điều hướng /staff/forgot-password 4) POST /api/staff/auth/forgot-password 5) Nếu email active: tạo staff_password_reset_requests (pending, hạn 24h), gửi email+in-app cho Admin 6) Trả 200 (luôn 200)",
     alt="A) Admin cấp mật khẩu tạm: GET /reset-requests, POST /issue-temp-password -> sinh 12 ký tự, hash lưu, must_change_password=1, thu hồi session, gửi email, ghi admin_audit_logs. B) Staff login mật khẩu tạm & đổi: must_change_password=1 -> limited_session 30 phút -> POST /change-temp-password.",
     exc="Yêu cầu hết hạn 24h -> 400 RESET_REQUEST_EXPIRED. Vượt rate limit -> 429. Mật khẩu mới yếu -> 422 WEAK_PASSWORD. Trùng mật khẩu tạm -> 422 SAME_PASSWORD.",
     priority="Should Have (P1)", freq="Không nêu",
     other="POST /api/auth/check-account-type; /api/staff/auth/forgot-password; GET /api/admin/staff/reset-requests; POST /issue-temp-password; POST /change-temp-password",
     assumptions="Không nêu",
     biz=[("BR-06-01","Chống email enumeration","Luôn trả 200 cho forgot-password"),
          ("BR-06-04","Không log mật khẩu tạm","Ở bất kỳ layer nào"),
          ("BR-06-06","Thu hồi session sau cấp mật khẩu tạm","Buộc đăng nhập lại mọi thiết bị"),
          ("BR-06-12","Audit mọi lần issue temp password","Ghi admin_audit_logs")],
     note="Mã 'UC-06' trong file gốc feat-auth/UC-06-staff-reset-password.md TRÙNG số với UC-06 'Learn Grammar' trong danh mục hợp nhất (Bao_cao_dac_ta_Use_Case.md) — đây là numbering cục bộ khác nhau giữa 2 tài liệu, KHÔNG phải cùng 1 use case. Đặt mã UC-AUTH-06 ở đây để tránh nhầm lẫn."),
]

assert len(UCS) == N, f"expected {N} UC, got {len(UCS)}"

for i, (rng, uc) in enumerate(zip(ranges, UCS), start=1):
    tabs = tables_in_range(doc, rng)
    fd, br = tabs[0], tabs[1]
    # heading 1.N
    head_el = rng[0]
    hp = Paragraph(head_el, doc)
    set_paragraph_text(hp, f"1.{i} {uc['code']}_{uc['name']}")
    # Functional Description table (15 rows x 4 cols)
    set_cell_text(fd.rows[0].cells[1], f"{uc['code']}_{uc['name']}")
    set_cell_text(fd.rows[1].cells[1], uc['created_by']); set_cell_text(fd.rows[1].cells[3], uc['date'])
    set_cell_text(fd.rows[2].cells[1], uc['actor']); set_cell_text(fd.rows[2].cells[3], uc['sec_actor'])
    set_cell_text(fd.rows[3].cells[1], uc['trigger'])
    set_cell_text(fd.rows[4].cells[1], uc['desc'])
    set_cell_text(fd.rows[5].cells[1], uc['pre'])
    set_cell_text(fd.rows[6].cells[1], uc['post'])
    set_cell_text(fd.rows[7].cells[1], uc['normal'])
    set_cell_text(fd.rows[8].cells[1], uc['alt'])
    set_cell_text(fd.rows[9].cells[1], uc['exc'])
    set_cell_text(fd.rows[10].cells[1], uc['priority'])
    set_cell_text(fd.rows[11].cells[1], uc['freq'])
    set_cell_text(fd.rows[12].cells[1], ", ".join(b[0] for b in uc['biz'] if b[0] != "—"))
    other = uc['other'] + ("\n" + uc.get('note','') if uc.get('note') else "")
    set_cell_text(fd.rows[13].cells[1], other)
    set_cell_text(fd.rows[14].cells[1], uc['assumptions'])
    # Business Rules table
    r0 = uc['biz'][0]
    set_cell_text(br.rows[1].cells[0], r0[0]); set_cell_text(br.rows[1].cells[1], r0[1]); set_cell_text(br.rows[1].cells[2], r0[2])
    for r in uc['biz'][1:]:
        last_tr = br.rows[-1]._tr
        new_tr = copy.deepcopy(last_tr)
        last_tr.addnext(new_tr)
        new_row = br.rows[-1]
        for ci, val in enumerate(r):
            set_cell_text(new_row.cells[ci], val)

# ---- 2. Xoa noi dung vi du GAMS con lai: "2. Common Functions" -> het truoc "III. Design Specifications" ----
del_range_before(doc, "2. Common Functions", "III. Design Specifications")
# ---- 3. Doi ten heading "1. <<Feature Name>>" thanh ten that ----
children = list(doc.element.body.iterchildren())
i_feat = find_paragraph_index(doc, "1. <<Feature Name>>")
set_paragraph_text(Paragraph(children[i_feat], doc), "1. Đặc Tả Chi Tiết Use Case (26/40 UC có tài liệu nguồn)")

doc.save("docs/07-Release-Documents/RDS_Document.docx")
print("Section II done.")
